package com.rumpus.common.views.Component;

import java.util.Map;

import com.rumpus.common.Manager.AbstractCommonManager;

/**
 * AbsrtactCommonManager for Quill objects.
 */
public class QuillManager extends AbstractCommonManager<String, Quill> {

    private QuillManager(boolean allowUseOfAutoGeneratedKey) {
        super(allowUseOfAutoGeneratedKey);
    }
    private QuillManager(Map<String, Quill> manageeMap, boolean allowUseOfAutoGeneratedKey) {
        super(manageeMap, allowUseOfAutoGeneratedKey);
    }
    
    public static QuillManager create(boolean allowUseOfAutoGeneratedKey) {
        return new QuillManager(allowUseOfAutoGeneratedKey);
    }
    public static QuillManager createWithMap(Map<String, Quill> manageeMap, boolean allowUseOfAutoGeneratedKey) {
        return new QuillManager(manageeMap, allowUseOfAutoGeneratedKey);
    }

    @Override
    public Quill createEmptyManagee(String name) {
        return this.put(name, Quill.createEmpty());
    }
    @Override
    public Quill createEmptyManagee() {
        return Quill.createEmpty();
    }
    @Override
    public String toString() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'toString'");
    }
}
