package com.rumpus.common.Dao.User.jdbc;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.Optional;

import javax.sql.DataSource;

import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;

import com.rumpus.common.ICommon;
import com.rumpus.common.Dao.User.IAuthorityDao;
import com.rumpus.common.Dao.jdbc.AbstractApiDBJdbc;
import com.rumpus.common.Log.ICommonLogger.LogLevel;
import com.rumpus.common.User.CommonAuthority;

/**
 * JDBC implementation of {@link IAuthorityDao}.
 *
 * <p>
 * This DAO manages the application's registered security authority
 * definitions. It is responsible only for the definitions themselves and
 * does not manage the assignment of authorities to users.
 * </p>
 *
 * <p>
 * User authority assignments are managed by {@code IUserAuthorityDao}.
 * </p>
 */
public class AuthorityDaoJdbc
        extends AbstractApiDBJdbc<CommonAuthority, Integer>
        implements IAuthorityDao {

    private static final String ID_COLUMN = "id";
    private static final String AUTHORITY_COLUMN = "authority";

    /**
     * Creates an authority DAO.
     *
     * @param dataSource
     *                   the JDBC data source
     * @param table
     *                   the authority definition table
     * @param mapper
     *                   row mapper used to construct {@link CommonAuthority}
     *                   instances
     */
    public AuthorityDaoJdbc(
            final DataSource dataSource,
            final String table,
            final RowMapper<CommonAuthority> mapper) {

        super(
                dataSource,
                table,
                mapper,
                Integer.class);
    }

    /**
     * Finds a registered authority by its authority name.
     *
     * @param authorityName
     *                      the authority name, for example
     *                      {@code ROLE_ADMIN}
     * @return the matching authority, or {@link Optional#empty()} if no
     *         matching authority exists
     */
    @Override
    public Optional<CommonAuthority> findByName(
            final String authorityName) {

        LOG_THIS("AuthorityDaoJdbc::findByName()");

        final String sql = String.format(
                "SELECT %s, %s FROM %s WHERE %s = ?",
                ID_COLUMN,
                AUTHORITY_COLUMN,
                this.tables().getMain(),
                AUTHORITY_COLUMN);

        return this.jdbc.query(
                sql,
                this.mapper,
                authorityName)
                .stream()
                .findFirst();
    }

    /**
     * Inserts a new authority definition.
     *
     * <p>
     * The authority ID is generated by the database. The ID supplied by the
     * model, if any, is intentionally ignored.
     * </p>
     *
     * @param model
     *              the authority definition to insert
     * @return the authority definition populated with its generated ID
     */
    @Override
    protected CommonAuthority doAdd(
            final CommonAuthority model) {

        LOG_THIS("AuthorityDaoJdbc::doAdd()");

        if (model == null) {
            throw new IllegalArgumentException(
                    "Authority cannot be null");
        }

        if (model.getAuthority() == null
                || model.getAuthority().isBlank()) {

            throw new IllegalArgumentException(
                    "Authority name cannot be null or blank");
        }

        final String sql = String.format(
                "INSERT INTO %s (%s) VALUES (?)",
                this.tables().getMain(),
                AUTHORITY_COLUMN);

        final KeyHolder keyHolder = new GeneratedKeyHolder();

        final int rows = this.jdbc.update(
                connection -> {

                    final PreparedStatement statement = connection.prepareStatement(
                            sql,
                            Statement.RETURN_GENERATED_KEYS);

                    statement.setString(
                            1,
                            model.getAuthority());

                    return statement;
                },
                keyHolder);

        if (rows != 1) {
            throw new IllegalStateException(
                    "Unable to insert authority '"
                            + model.getAuthority()
                            + "'");
        }

        final Number generatedId = keyHolder.getKey();

        if (generatedId == null) {
            throw new IllegalStateException(
                    "Authority '"
                            + model.getAuthority()
                            + "' was inserted, but no generated ID "
                            + "was returned");
        }

        final Integer authorityId = generatedId.intValue();

        CommonAuthority updatedAuthority = new CommonAuthority(model.getAuthority());
        updatedAuthority.setId(authorityId);
        return updatedAuthority;
    }

    /**
     * Updates an existing authority definition.
     *
     * <p>
     * The authority ID is immutable. Only the authority name is updated.
     * </p>
     *
     * @param id
     *              the identifier of the authority to update
     * @param model
     *              the new authority definition
     * @return the updated authority definition
     */
    @Override
    protected CommonAuthority doUpdate(
            final Integer id,
            final CommonAuthority model) {

        LOG_THIS("AuthorityDaoJdbc::doUpdate()");

        if (id == null) {
            throw new IllegalArgumentException(
                    "Authority ID cannot be null");
        }

        if (model == null) {
            throw new IllegalArgumentException(
                    "Authority cannot be null");
        }

        if (model.getAuthority() == null
                || model.getAuthority().isBlank()) {

            throw new IllegalArgumentException(
                    "Authority name cannot be null or blank");
        }

        final String sql = String.format(
                "UPDATE %s SET %s = ? WHERE %s = ?",
                this.tables().getMain(),
                AUTHORITY_COLUMN,
                ID_COLUMN);

        final int rows = this.jdbc.update(
                sql,
                model.getAuthority(),
                id);

        if (rows != 1) {
            throw new IllegalArgumentException(
                    "Unable to update authority with ID '"
                            + id
                            + "'");
        }

        CommonAuthority updatedAuthority = new CommonAuthority(model.getAuthority());
        updatedAuthority.setId(id);
        return updatedAuthority;
    }

    /**
     * Returns a string representation of this DAO.
     *
     * @return a description of this DAO and its configured table
     */
    @Override
    public String toString() {

        return "AuthorityDaoJdbc{"
                + "table='"
                + this.tables().getMain()
                + '\''
                + '}';
    }

    private static void LOG_THIS(String... args) {
        ICommon.LOG(AuthorityDaoJdbc.class, args);
    }

    private static void LOG_THIS(LogLevel level, String... args) {
        ICommon.LOG(AuthorityDaoJdbc.class, level, args);
    }
}
